Respect `with_locals` setting
kiwicom/structlog-sentry pull request #74
Opened 2022-08-04 15:15 UTC by alxwrd

Hi!

This is a patch to use the `with_locals` setting from the Sentry client when creating an event.

[`with_locals`](https://docs.sentry.io/platforms/python/configuration/options/#with-locals) is a setting you can enable when initialising the Sentry SDK (

```python
sentry_sdk.init(
    with_locals=False,
    ...
)
```

) that can turn off local varibales being displayed with each stackframe.

[`event_from_exception`](https://github.com/getsentry/sentry-python/blob/8b1e8ce5f69265016ccc640b86ea1573749e23aa/sentry_sdk/utils.py#L739) uses it's own "`client_options`" which is used when [creating the frames](https://github.com/getsentry/sentry-python/blob/8b1e8ce5f69265016ccc640b86ea1573749e23aa/sentry_sdk/utils.py#L562-L570).

2022-08-04 15:48 UTC, alxwrd commented
- https://github.com/kiwicom/structlog-sentry/pull/74

2022-08-09 17:30 UTC, alxwrd commented
Current work around

```python
import functools

import sentry_sdk
import structlog
import structlog_sentry

structlog_sentry.event_from_exception = functools.partial(
    structlog_sentry.event_from_exception,
    client_options={
        "with_locals": sentry_sdk.Hub.current.client.options.get("with_locals")
    },
)

structlog.configure(
    processors=[structlog_sentry.SentryProcessor],
)
```

2022-08-19 14:52 UTC, paveldedik commented
Hi @alxwrd Thank you for the PR, could you please rebase your branch onto master? There are going to be some changes (you will definitely need to update tests).

For all changes see https://github.com/kiwicom/structlog-sentry/pull/79

2022-08-19 16:44 UTC, alexward-plutoflume commented
hi @paveldedik, thank you. That's done :)

2022-08-19 16:44 UTC, alxwrd commented
hi @paveldedik, thank you. That's done :)

2022-08-20 17:03 UTC, paveldedik requested changes
Thank you for the PR, it looks good :-), I have just a minor thing.

Also please rebase again (sorry for that, the CI weren't running for your branch so I fixed that in master).

2022-08-20 17:03 UTC, paveldedik commented on test/test_sentry_processor.py
> +    with unittest.mock.patch.object(SentryProcessor, "_get_hub") as mock__get_hub:
Could you please use `sentry_events` fixture instead? It does not require mocking and it contains captured sentry events. For inspiration see other tests.

2022-08-20 17:03 UTC, paveldedik commented on test/test_sentry_processor.py
> +    with unittest.mock.patch.object(SentryProcessor, "_get_hub") as mock__get_hub:
The same as above.

2022-08-25 10:48 UTC, alxwrd commented
hi @paveldedik - I've updated the tests and rebased.

To pass the configuration into `sentry_sdk.Client`, I've used `@pytest.mark.parametrize` with a notion of `ClientParams`. If you'd rather this doing a different way, let me know.

2022-08-25 12:00 UTC, paveldedik approved these changes
Thank you! I like this approach :-)

2022-08-25 12:00 UTC, merged